### ISSUE TITLE
Command line fails to update when starting with F10

### ISSUE THREAD

**Issue by krilbe** [MBulli/SmartCommandlineArgs#65] opened 2018-09-14 14:53 UTC
If a debug session is started with F5, the command line seems to be properly set according to the SmartCommandlineArgs settings, but not if the debug session is started with F10 (Step over). 

I have not tested F11 etc. You probably should check all possible ways to start a debug session.

Tested with VS 2017 community on a C# .NET Framework 4.7.1 console application.

**Comment by MBulli** [comment] 2018-09-16 09:35
Well the problem is that we're not aware of any event which just tells us if the program is started. I can handle the StepOver/StepIn Commands etc. but I also need to know if the program is already been debugged.

**Comment by krilbe** [comment] 2018-09-16 09:55
Alright, I understand. Not so easy to fix then. I can live with it. :-)

**Comment by MBulli** [comment] 2018-09-16 10:06
Still we try to fix it ;)

**Comment by Irame** [comment] 2024-12-07 15:35
With [v3.2](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v3.2.0) the args are updated whenever the args configured in the extension change. We still update them again when we receive an event that indicates the start of a debug session, just to be sure.
So this should technically resolve the issue, therefore I'm closing it.

**Closed** 2024-12-07 15:35 UTC
Labels: bug
