### ISSUE TITLE
Construction of frame content failed

### ISSUE THREAD

**Issue by wilsade** [MBulli/SmartCommandlineArgs#53] opened 2018-05-07 11:46 UTC
I am having troubles using the extension.
It does not load. Commandline Arguments window stays blank.
I am using Visual Studio 2017 Enterprise 15.6.7.
Here is the Activitylog.xml

<description>Construction of frame content failed.&#x000D;&#x000A;Frame identifier: ST:0:0:{a21b35ed-5c13-4d55-a3d2-71054c4e9540}&#x000D;&#x000A;Frame caption: Commandline Arguments&#x000D;&#x000A;Exception details:&#x000D;&#x000A;System.Exception: Exception of type &apos;System.Exception&apos; was thrown.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid&amp; packageGuid, Int32 reason, Guid&amp; context)&#x000D;&#x000A;   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()&#x000D;&#x000A;   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()</description>

Thanks

**Comment by MBulli** [comment] 2018-05-08 07:37
Sadly the log is not really helpful. We need more details to figure out the problem.
Would you mind to provide [a full log](https://github.com/MBulli/SmartCommandlineArgs/wiki/Debug-Log).

Does the exception occur every time or only in a specific scenario? Does it happen if a solution is open or closed? Which project types are you using? Which workloads (C#, C++, Xamarin etc.) have you installed?

**Comment by MBulli** [comment] 2018-05-13 01:25
To be honest I have no idea whats wrong here. But according to [this issue](https://github.com/Microsoft/PTVS/issues/1391) and [that one](https://github.com/NuGet/Home/issues/3042) deleting the `%localappdata%\Microsoft\VisualStudio\YOUR-VERSION\ComponentModelCache` could solve the problem.

**Comment by MBulli** [comment] 2018-05-22 19:35
I'll close this one, feel free to reopen if the problem is still there.

**Closed by MBulli** 2018-05-22 19:35 UTC
