### ISSUE TITLE
Operating on one project's command line panel affects other projects

### ISSUE THREAD

**Issue by DominikGrabiec** [MBulli/SmartCommandlineArgs#101] opened 2020-05-04 14:38 UTC
I'm using the extension at work where there are multiple executable projects in our large solution. Whenever I do an action in one project it does operation in another project. I'm using json storage for the options, not the suo file.

There have been multiple instances of this happening so I've taken the time to report it.

- Moving or deleting items from one project's also deletes / moves items in other projects.
- Copying a single row from one project and pasting it, has pasted several entries from multiple projects.
- Deleting these extra entries has also deleted them from the other projects.

This makes the extension rather unreliable to work with.

**Comment by MBulli** [comment] 2020-05-09 16:09
Sorry, can't reproduce the issue ...
Can you please provide more information?

What VS version? Does it happen all the time? What project kinds are you using? How large is the solution?

**Comment by DominikGrabiec** [comment] 2020-05-11 17:13
Visual Studio 2017, version 15.9.22, although it affected earlier versions as well.
Smart Command Line Arguments version 2.2.0.
The solution has about 270 projects created with Premake for several platforms.

Can confirm that copying a single entry from one project and pasting it in another one causes multiple lines to be pasted, from all different projects. I suspect this has to do with selected lines in the panel as the one which are selected get pasted. 
If I then delete one of the pasted lines it also deletes it from the given project.

**Comment by Irame** [comment] 2021-12-24 22:52
Sorry for not looking into such an severe bug for such along time. I couldn't replicate the issue you had exactly but I think it has to do with the fact that the selection isn't cleared properly in some occasions. This should be fixed in the next version
 (see d7b02c192b3a3ed32f934ec66fabc073c8af06cb and 1a658d4ab538954767367ec404cfc27723653ff1).

**Closed by Irame** 2021-12-24 22:52 UTC
