### ISSUE TITLE
Data Loss when moving elements inside folders

### ISSUE THREAD

**Issue by DominikGrabiec** [MBulli/SmartCommandlineArgs#86] opened 2019-08-14 10:22 UTC
Had a rather long list of arguments and I wanted to group them to make them easier to manage.

- Create a group normally, renamed, moved elements into it. 
- Created other groups by selecting elements and right clicking "New group from selection". 
- Moved elements up and down using Alt+Up/Down arrows **but instead of moving the elements it was shifting elements in other groups all over the place**. 
- Then I collapsed the folders so I could see how the list looked like now, but **when I expanded them I lost most of the entries in the lists**.

Folders which had many entries in them (5+) now contained only a single one. Other folders had entries missing, and because the JSON file saved automatically I had to go to a really old backup to restore the command line parameters.

**Comment by MBulli** [comment] 2019-09-01 09:49
Sorry for the data loss! This sounds like that the selection of the elements was messed up internally. Right now I can't reproduce this behavior. Usually there is one important detail on how to trigger the erratic behavior. Does is happen all the time to you?

**Comment by MBulli** [comment] 2019-09-22 13:56
Irame told me that he couldn't reproduce the error but reworked some code parts related to this in 713364ae5742bdd99a459a619f63f16d14073d3b. So it might be fixed in the next version.

**Closed by MBulli** 2019-09-22 13:56 UTC
